project:
  type: book
  output-dir: docs

book:
  title: "From Questions to Transformation"
  subtitle: "A Practitioner's Guide to Inquiry-Based Educational Reform"
  author: "Jian Huang"
  search: true
  page-footer: "Copyright 2025 Proofbound, Inc"
  site-url: https://ensembio.github.io/book-china-education/
  downloads: [pdf, epub]
  date: "6/10/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - ch1-foundations.qmd
    - ch2-consensus.qmd
    - ch3-top-level-design.qmd
    - ch4-three-questions.qmd
    - ch5-leadership.qmd
    - ch6-scaling.qmd
    - ch7-teacher-development.qmd
    - ch8-pitfalls.qmd
    - ch9-assessment.qmd
    - ch10-sustainability.qmd
    - summary.qmd
    # - references.qmd

bibliography: references.bib

format:
  html:
    theme: minty
    css: _resources/book/css/normalize.css
    standalone: true
    toc: true
    link-external-newwindow: true
  pdf:
    papersize: "Letter"
    mainfont: "Georgia"
    CJKmainfont: "STSong"  # or another CJK font you have installed
    toc: true
    documentclass: scrbook
    geometry: paperwidth=6in,paperheight=9in
    standalone: true
    toc-depth: 2  
    keep-tex: true
    include-in-header:
      - text: |
          \usepackage{xeCJK}
          \setCJKmainfont{STSong}
    header-includes:
      - \raggedbottom